### ISSUE TITLE
Loading pack cache feature will cause game crash

### ISSUE THREAD

**Issue by RaKGEKKO** [SettingDust/lazyyyyy#44]
lazyyyyy freezes at finishing mod loading and never ends.

Here is the latest log.

[latest.log](https://github.com/user-attachments/files/19395576/latest.log)

**Comment by RaKGEKKO** [comment]
Apparently it was caused by this option right here.

![Image](https://github.com/user-attachments/assets/9792163a-955f-452b-beb0-0e85dd55bf85)

**Comment by RaKGEKKO** [comment]
But the previous bug about the massive lag still persists.

**Comment by SettingDust** [comment]
I can reproduce with your pack but can't figure what's the mod conflicting. Can you find out?

**Comment by RaKGEKKO** [comment]
Maybe, i have a clue on where to start, i updated it 1 day after it got updated so its a mod that i installed on that day.

**Comment by RaKGEKKO** [comment]
BTW, i realized two days ago it was an incompatibility and not an update problem, because the 7.14 didn't work too so probably was my fault.

**Comment by RaKGEKKO** [comment]
Oh and last thing before i continue testing, i tried disabling all options of Lazyyyyy to see if the issue persisted, and it did, idk why.

**Comment by RaKGEKKO** [comment]
smth i realized its that with lazyyyyy it lags out a lot when generating chunks and principally lags tps, maybe it has to do with some mod related on that zone of performance.

**Comment by SettingDust** [comment]
providing the spark profile for your lagging

**Comment by RaKGEKKO** [comment]
Hey im not 100% sure, but i think i found the culprit.

**Comment by RaKGEKKO** [comment]
I think its performant by someaddon.

**Comment by RaKGEKKO** [comment]
Because when i tested without it it was actually stable in comparison when it was with it, and it should be really unstable because it literally its the main performance mod of my modpack so i think it may be an incompatibility with performant.

**Comment by SettingDust** [comment]
I don't know what's the issue you are talking here. providing the spark profile for your lagging

**Comment by RaKGEKKO** [comment]
Oh wait i was talking about the lagging tps, the previous issue i had.

**Comment by RaKGEKKO** [comment]
i have it since the version 8.0 remember?

**Comment by RaKGEKKO** [comment]
Again sorry if i am explaining myself poorly i don't speak english.

**Comment by SettingDust** [comment]
> providing the spark profile for your lagging

**Comment by RaKGEKKO** [comment]
How do i do that?

**Comment by SettingDust** [comment]
https://spark.lucko.me/
https://spark.lucko.me/docs/Command-Usage#spark-profiler

**Comment by RaKGEKKO** [comment]
Idk exactly how to do that but ill try.

**Comment by SettingDust** [comment]
https://modrinth.com/mod/spark

**Comment by RaKGEKKO** [comment]
How do i send it to you?

**Comment by RaKGEKKO** [comment]
If i send it inside a zip file its good?

**Comment by SettingDust** [comment]
https://spark.lucko.me/docs/Using-the-viewer

**Comment by RaKGEKKO** [comment]
Okay and now what?

**Comment by SettingDust** [comment]
> [spark.lucko.me/docs/Using-the-viewer](https://spark.lucko.me/docs/Using-the-viewer)

> Once you have created a profile using the [/spark profiler](https://spark.lucko.me/docs/Command-Usage#spark-profiler) command, your profile will be automatically uploaded to the viewer, and you will be presented with a link.
> 
> You can freely share this link with other people, send it to someone helping you or to a plugin/mod developer to point out a problem!

**Comment by RaKGEKKO** [comment]
well something weird happened when i used stop on the profiler because it crashed and didn't give the link.

**Comment by RaKGEKKO** [comment]
![Image](https://github.com/user-attachments/assets/897575ba-e33d-42df-aed1-d4470c50b20a)

**Comment by SettingDust** [comment]
Send the file as zip here

**Comment by RaKGEKKO** [comment]
[spark.zip](https://github.com/user-attachments/files/19401618/spark.zip)

**Comment by SettingDust** [comment]
Can't see any lagging in your profile. Are you sure your server(TPS) or client is lagging?

**Comment by RaKGEKKO** [comment]
Yeah idk why it seems normal there, but on game it was literally generating chunks slowly i could even get on the unloaded chunks zone, also 30- fps and if i pressed alt+f3 it literally was everything red/orange.

And without lazyyyyy it goes a lot better.

**Comment by SettingDust** [comment]
Start a spark profiler when you are loading the chunks.

**Comment by RaKGEKKO** [comment]
Thats what i did, i was literally flying through chunks.

**Comment by SettingDust** [comment]
Ensure all the time when the profiler running the game is lagging

**Comment by SettingDust** [comment]
Again. What's lagging. FPS or TPS

**Comment by RaKGEKKO** [comment]
It was, thats why am surprised it looked good on the spark profiler, because i literally couldn't play without it lagging.

**Comment by RaKGEKKO** [comment]
I think i should just stop trying to fix this, because it seems like there isn't any clue on what may be breaking lazyyyyy.

So i think its better if i just don't use it for now.

**Comment by RaKGEKKO** [comment]
And i am also making you work without making any progress so i think its better if you focus on other things rather than my problem.

**Comment by SettingDust** [comment]
I'll look into the lagging after this freezing issue

**Comment by RaKGEKKO** [comment]
Oh about the freezing issue, i think its caused by a mod called RPC or Resourcepack cached, that may interfere with your mixins with lazyyyyy.

**Comment by RaKGEKKO** [comment]
Btw why reopen? The bug was fixed atleast when you modify the config.

**Comment by SettingDust** [comment]
It's not fixed.

The 0.9.0 is published with the new changes from https://github.com/SettingDust/lazyyyyy/tree/feature/pack-loading-cache
Which isn't exists in the 0.8.x

**Comment by RaKGEKKO** [comment]
Oh i didnt know.

**Comment by RaKGEKKO** [comment]
Fixed on new update (atleast for me)

**Comment by RaKGEKKO** [comment]
btw should i activate async model baking?

**Comment by SettingDust** [comment]
> Fixed on new update (atleast for me)

> The 0.9.0 is published with the new changes from [feature/pack-loading-cache](https://github.com/SettingDust/lazyyyyy/tree/feature/pack-loading-cache?rgh-link-date=2025-04-03T05%3A42%3A56.000Z)
> Which isn't exists in the 0.8.x


> btw should i activate async model baking?

No, will affect fps

**Comment by RaKGEKKO** [comment]
Okay ill close the issue but uust so you know im still using previous version because last one lags a lot for some reason.

**Comment by SettingDust** [comment]
What's the version lagging a lot.
0.9.0 is archived. The latest is 0.8.x

**Comment by RaKGEKKO** [comment]
Yeah the last 0.8.x

**Comment by RaKGEKKO** [comment]
.12

**Comment by SettingDust** [comment]
The freeze causing by https://github.com/RelativityMC/C2ME-fabric/issues/426
The subject of this issue changed

**Comment by SettingDust** [comment]
The crash report is avoided by another bug https://github.com/txnimc/SodiumDynamicLights/issues/53

**Comment by RaKGEKKO** [comment]
> For the 0.8.12 lagging. Spark profile. Since there isn't anything relating to the in game. I don't think it's specific to 0.8.12.

It is. Idk why but 0.8.11 works perfectly but 0.8.12 dont
