### ISSUE TITLE
[Forge 1.20.1] ImmersiveEngineering overwriting all the renderers

### ISSUE THREAD

**Issue by Apollonu** [SettingDust/lazyyyyy#66]
Everytime an entity renders, it has a quick texture error then reverts to normal and the error shows in the log. All of the logs look similar to this.

```
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(Lazy Entity Renderer entity.minecraft.chicken), LazyDeferredCoroutine{Completed}@72f30fd7, Dispatchers.IO]
Caused by: java.lang.UnsupportedOperationException
	at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.collect.ImmutableMap.put(ImmutableMap.java:780)
	at TRANSFORMER/lazyyyyy.xplat.lexforge@0.14.6/settingdust.lazyyyyy.minecraft.LazyEntityRenderer.loading$lambda$1$lambda$0(LazyEntityRenderers.kt:90)
	at LAYER PLUGIN/thedarkcolour.kotlinforforge@4.11.0-all/kotlinx.coroutines.InternalCompletionHandler$UserSupplied.invoke(CompletionHandler.common.kt:67)
	at LAYER PLUGIN/thedarkcolour.kotlinforforge@4.11.0-all/kotlinx.coroutines.InvokeOnCompletion.invoke(JobSupport.kt:1392)
	at LAYER PLUGIN/thedarkcolour.kotlinforforge@4.11.0-all/kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1502)
	... 14 more
```

[latest.log](https://github.com/user-attachments/files/20108758/latest.log)

**Comment by SettingDust** [comment]
I need to reproduce. It's weird. I guess it's conflicting with some other mods

**Comment by Apollonu** [comment]
Would you like me to send the modpack? All you should have to do is update lazyyyyy. The same errors should show, all I have done is update mods.

**Comment by Apollonu** [comment]
[Abaddon Mines - 0.1.5-InDev.zip](https://github.com/user-attachments/files/20112876/Abaddon.Mines.-.0.1.5-InDev.zip)

**Comment by SettingDust** [comment]
Can't reproduce

**Comment by SettingDust** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/blob/1.20.1/src/main/java/blusunrize/immersiveengineering/client/render/entity/ShaderMinecartRenderer.java#L175-L191
[ImmersiveEngineering](https://github.com/BluSunrize/ImmersiveEngineering/tree/1.20.1) is overwriting the renderers :(((

**Comment by SettingDust** [comment]
should be fixed in 0.14.8

**Comment by SettingDust** [comment]
waiit. It will overwrite the renderer everytime add layers. I need to add extra compat with it for the minecart renderer from it working

**Comment by SettingDust** [comment]
should be fixed in 0.14.9

**Comment by Apollonu** [comment]
The issue persists in 0.14.9
```
Exception in thread "DefaultDispatcher-worker-74" kotlinx.coroutines.CompletionHandlerException: Exception in completion handler InvokeOnCompletion@f26a2c3[job@ca1cd85] for LazyDeferredCoroutine{Completed}@ca1cd85
	at LAYER PLUGIN/thedarkcolour.kotlinforforge@4.11.0-all/kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1506)
	at LAYER PLUGIN/thedarkcolour.kotlinforforge@4.11.0-all/kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:322)
	at LAYER PLUGIN/thedarkcolour.kotlinforforge@4.11.0-all/kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:239)
	at LAYER PLUGIN/thedarkcolour.kotlinforforge@4.11.0-all/kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:917)
	at LAYER PLUGIN/thedarkcolour.kotlinforforge@4.11.0-all/kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:874)
	at LAYER PLUGIN/thedarkcolour.kotlinforforge@4.11.0-all/kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:839)
	at LAYER PLUGIN/thedarkcolour.kotlinforforge@4.11.0-all/kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:97)
	at LAYER PLUGIN/thedarkcolour.kotlinforforge@4.11.0-all/kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at LAYER PLUGIN/thedarkcolour.kotlinforforge@4.11.0-all/kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at LAYER PLUGIN/thedarkcolour.kotlinforforge@4.11.0-all/kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at LAYER PLUGIN/thedarkcolour.kotlinforforge@4.11.0-all/kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at LAYER PLUGIN/thedarkcolour.kotlinforforge@4.11.0-all/kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at LAYER PLUGIN/thedarkcolour.kotlinforforge@4.11.0-all/kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at LAYER PLUGIN/thedarkcolour.kotlinforforge@4.11.0-all/kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at LAYER PLUGIN/thedarkcolour.kotlinforforge@4.11.0-all/kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(Lazy Entity Renderer entity.minecraft.cave_spider), LazyDeferredCoroutine{Completed}@ca1cd85, Dispatchers.IO]
Caused by: java.lang.UnsupportedOperationException
	at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.collect.ImmutableMap.put(ImmutableMap.java:780)
	at TRANSFORMER/lazyyyyy.xplat.lexforge@0.14.9/settingdust.lazyyyyy.minecraft.LazyEntityRenderer.loading$lambda$1$lambda$0(LazyEntityRenderers.kt:90)
	at LAYER PLUGIN/thedarkcolour.kotlinforforge@4.11.0-all/kotlinx.coroutines.InternalCompletionHandler$UserSupplied.invoke(CompletionHandler.common.kt:67)
	at LAYER PLUGIN/thedarkcolour.kotlinforforge@4.11.0-all/kotlinx.coroutines.InvokeOnCompletion.invoke(JobSupport.kt:1392)
	at LAYER PLUGIN/thedarkcolour.kotlinforforge@4.11.0-all/kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1502)
	... 14 more
```

[latest.log](https://github.com/user-attachments/files/20125220/latest.log)

**Comment by SettingDust** [comment]
The log has no error you provided hm

**Comment by SettingDust** [comment]
And I can't reproduce

**Comment by Apollonu** [comment]
This is the modpack that I have been using that the issue is occuring in: https://www.curseforge.com/minecraft/modpacks/abaddon-mines/files/6511139

I have updated lazyyyyy and ran it, The log is below.

[latest.log](https://github.com/user-attachments/files/20130335/latest.log)

**Comment by SettingDust** [comment]
sad. I can't reproduce with the pack in link and upadted lazyyyyy. I will publish the latest lazyyyyy

**Comment by SettingDust** [comment]
The latest 0.14.10 fixed #68 and avoid suppress the error you said above

**Comment by Apollonu** [comment]
It appears to show in console this time, and seems to only appear the first time an entity is rendered.
[latest.log](https://github.com/user-attachments/files/20131055/latest.log)

**Comment by SettingDust** [comment]
I need to repriduce. pAiN

**Comment by SettingDust** [comment]
How are you reproducing? Open the title screen?

**Comment by Apollonu** [comment]
I create a world and you can either wait for the error to show or you can spawn any entity in and it will show in the log.

**Comment by SettingDust** [comment]
It's not relating to ImmersiveEngineering. Can't figure out :((

**Comment by Apollonu** [comment]
It looks like the issue has gone away after updating some mods, I will reopen this if the issue comes back.

**Comment by SettingDust** [comment]
hm. fine

**Comment by SettingDust** [comment]
Can you find out the minimal reproducible mod set? I can't reproduce with only ImmersiveEngineering hm

**Comment by Apollonu** [comment]
A modpack without these did not have the error, im going to check if I cannot find the one responsible

```
- abridged 1.1.1
- ad_astra 1.15.20
- backpacked 3.0.0-beta.9
- baguettelib 1.0.0
- biomeswevegone 1.5.11
- blockswap 5.0.0.0
- blueprint 7.1.3
- botarium 2.3.4
- caveoverhaul 1.3.4
- configured 2.2.3
- corgilib 4.0.3.3
- create 6.0.4
- create_ad_astra_compat 1.0.0
- create_mechanical_extruder 1.20.1-1.6.9-6.0.4
- create_new_age 1.1.4
- createaddition 1.20.1-1.3.1
- createlowheated 1.20.1-6.0.2-3
- createpickywheels 1.20.1-6.0.0-1
- curios 5.14.1+1.20.1
- deeper_oceans 1.0.1a
- elysium_api 1.1.2
- engineered_schematics 1.2.2
- enhancedai 2.6.2
- everythingcopper 1.20.1-2.3.4
- geckolib 4.7.1.2
- gravestone 1.20.1-1.0.24
- gravestonecurioscompat 3.0.0
- hltweaker 1.3.0
- htm 1.0.8
- immersiveengineering 1.20.1-10.2.0-183 //Possible Cause
- industrialforegoing 3.5.19 //Possible Cause
- insanelib 1.19.0
- jei_mekanism_multiblocks 4.10
- jeimultiblocks 1.0.4
- kjsindustrialforegoing 1.0
- kubejs_create 2001.3.0-build.8
- kubejs_immersive_engineering 2001.1.5-build.19
- lootjs 1.20.1-2.13.0
- lychee 5.1.19+forge
- map_atlases 1.20-6.0.16
- mekanism 10.4.15
- mekanismaaa 1.1.0
- mekanismgenerators 10.4.15
- mobspropertiesrandomness 4.10.16
- moremekanismprocessing 4.3
- netherexp 2.3.2
- notreepunching 7.1.0
- ohthetreesyoullgrow 1.3.9
- oreganized 3.1.4
- patchouli 1.20.1-84.1-FORGE
- pneumaticcraft 6.0.20+mc1.20.1
- resourcefullib 2.1.29
- silentgear 3.6.6
- silentlib 8.0.0
- spelunkery 1.20.1-0.3.16
- swl 0.2.1g-mixin-forge-1.20.1
- tectonic 2.0
- terrablender 3.0.1.10
- terrablenderfix 0.0.1
- tfmg 0.9.3b-fix-1.20.1 //Possible Cause
- tfmgjs 1.20.1-1.2.0
- titanium 3.8.32
- vintage 1.20.1-1.1.0 //Possible Cause
- volcanic_caverns 1.2.5.1
\-- fabric_screen_handler_api_v1 1.3.30+561530ec77
\-- mixinextras 0.5.0-beta.5
\-- ponder 1.0.52
|-- fabric_transfer_api_v1 3.3.5+631c9cd677
|-- flywheel 1.0.2
```

**Comment by SettingDust** [comment]
> I can't reproduce with only ImmersiveEngineering

Can you?

**Comment by Apollonu** [comment]
Caused by Fancy TESR, there is a config option to disable it in Immersive Engineering.

**Comment by SettingDust** [comment]
hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm

**Comment by Apollonu** [comment]
> `mixin.perf.dynamic_entity_renderers`?

These are the only two I have changed
```
mixin.bugfix.missing_block_entities=true
mixin.perf.faster_item_rendering=true
```

**Comment by Apollonu** [comment]
https://github.com/SettingDust/lazyyyyy/issues/66 and https://github.com/SettingDust/lazyyyyy/issues/78 could have been caused by Flerovium (or palladium, less likely), I removed it from my modpack(s) a bit ago due to other issues and it _seems_ to be fixed (hopefully forever).
I launched twice and it seems to be fine and the weird skin issue and error when spawning an animal is gone too (hopefully forever). This is the closest thing I could find to resolve this finally. I really will be lost if I have to leave the issue open as to what it could be.

I will leave the issue(s) open for you to confirm, since my testing may get interrupted by other mods and so you can test the validity of the mod interferring.
<img width="1920" height="1012" alt="Image" src="https://github.com/user-attachments/assets/7ad9f428-2d49-4f11-9e46-9f2b1a2cce8a" />
